### ISSUE TITLE
Treinen rijden niet, wat moet ik doeN?

### ISSUE THREAD

**Issue by AshlynDev** [arte921/annod#1]
Ik zou graag iets willen berekenen maar omdat de treinen niet rijden heeft het geen zin, hoe kan ik dit fixen?

**Comment by arte921** [comment]
Ja

**Comment by BennovanDorst** [comment]
ja nee daar heb ik niks aan potverdikkie

**Comment by arte921** [comment]
Heeft meer cloud™️ nodig
